### PR TITLE
Add a codename to versions

### PR DESCRIPTION
**Pull request by maniksurtani**

### CODE REVIEW

**Comment by pmuir** [comment]
+1 this looks good to me

**Comment by maniksurtani** [comment]
Tests pass too.

**Comment by LightGuard** [comment]
:+1: :beer:

**Comment by hannelita** [comment]
Awesome! :tulip:

**Comment by maniksurtani** [comment]
I must give credit to @nmcl for the code name suggestion.  I vote for Edelweiss for version.next...

**Pull request closed without merging**
